apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}
  labels:
    app: {{ include "client.name" . }}
    release: {{ .Release.Name }}
    component: client-service
spec:
  type: {{ .Values.clientService.service.type }}
  ports:
    - port: {{ .Values.clientService.service.port }}
      targetPort: {{ .Values.clientService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "client.name" . }}
    release: {{ .Release.Name }}
