apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    app: {{ include "eureka.name" . }}
    release: {{ .Release.Name }}
    component: eureka-server
  {{- with .Values.eureka.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.eureka.service.type }}
  ports:
    - port: {{ .Values.eureka.service.port }}
      targetPort: {{ .Values.eureka.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "eureka.name" . }}
    release: {{ .Release.Name }}
