apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app: {{ include "gateway.name" . }}
    release: {{ .Release.Name }}
    component: gateway-service
spec:
  type: {{ .Values.gatewayService.service.type }}
  ports:
    - port: {{ .Values.gatewayService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "gateway.name" . }}
    release: {{ .Release.Name }}
