apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app: {{ include "web.name" . }}
    release: {{ .Release.Name }}
    component: web-app
spec:
  replicas: {{ .Values.webApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "web.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "web.name" . }}
        release: {{ .Release.Name }}
        component: web-app
    spec:
      securityContext:
        {{- toYaml .Values.webApp.securityContext | nindent 8 }}
      containers:
        - name: web-app
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag }}"
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webApp.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
            - name: env-config-volume
              mountPath: /usr/share/nginx/html/public/env.js
              subPath: env.js
              readOnly: true
          resources:
            {{- toYaml .Values.webApp.resources | nindent 12 }}
        #   livenessProbe:
        #     httpGet:
        #       path: /health
        #       port: http
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     failureThreshold: 3
        #   readinessProbe:
        #     httpGet:
        #       path: /health
        #       port: http
        #     initialDelaySeconds: 5
        #     periodSeconds: 5
        #     failureThreshold: 3
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ include "web.configmap.name" . }}-nginx
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: env-config-volume
          configMap:
            name: {{ include "web.configmap.name" . }}-env
            items:
              - key: env.js
                path: env.js
