apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app: {{ include "web.name" . }}
    release: {{ .Release.Name }}
    component: web-app
spec:
  type: {{ .Values.webApp.service.type }}
  ports:
    - port: {{ .Values.webApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "web.name" . }}
    release: {{ .Release.Name }}
